version: "3"

services:
  api:
    build: ./api
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./api:/usr/src/klisi_api
    ports:
      - 443:443

  web:
    build: ./client
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./client:/usr/src/klisi_client
    ports:
      - 3000:3000