version: "3"

services:
  klisi-api:
    build: ./api
    volumes:
      - ./api:/usr/src/klisi_api
    ports:
      - 443:443

  klisi-web:
    build: ./client
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./client:/usr/src/klisi_client
    ports:
      - 3000:3000
    depends_on: 
      - klisi-api